#!/usr/bin/env python3
"""
AI Portfolio Dashboard - backend + static server (zero dependencies, stdlib only).

Data source
-----------
All numbers come from a synthetic industrial dataset in SQLite (dashboard.db),
generated by seed.py from real statistical models (Weibull reliability, Poisson
defects/incidents, trend+seasonality demand, OEE = A x P x Q, ...). This server
*aggregates* those raw rows into the figures each dashboard widget shows - there
are no hardcoded data values. If the DB is missing it is seeded automatically.

Run:  python server.py            # serves on http://127.0.0.1:8000
      python server.py 8080       # custom port

Endpoints
---------
  GET /api/health            -> {status, time}
  GET /api/modules           -> nav metadata
  GET /api/module/<id>       -> aggregated widget data for one module
  GET /api/reseed            -> rebuild the dataset (new random factory)
"""

import json
import math
import os
import sqlite3
import sys
import time
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

import seed  # local module (seed.py)
import live  # local module (live.py) - real public-internet data

ROOT = Path(__file__).resolve().parent
DB_PATH = Path(os.environ.get("DASHBOARD_DB", str(ROOT / "dashboard.db")))


# Map a marker on the 320x170 equirectangular world SVG back to lat/lon, so we
# can compare a simulated supplier's location against live earthquakes/weather.
def pixel_to_latlon(x, y):
    lon = (x / 320.0) * 360.0 - 180.0
    lat = 90.0 - (y / 170.0) * 180.0
    return lat, lon

MODULES = [
    {"id": "revenue", "label": "Revenue", "short": "Module 1",
     "title": "Revenue Growth & Customer Intelligence",
     "subtitle": "Personalized journeys, smarter pricing, and AI-powered demand "
                 "forecasting that unlock new revenue streams."},
    {"id": "commercial", "label": "Commercial Operations", "short": "Module 2",
     "title": "Commercial Operations & AI-Assisted Support",
     "subtitle": "Prioritized cases, intelligent support, and supplier insight "
                 "that compress decision cycles."},
    {"id": "plant", "label": "Plant Performance", "short": "Module 3",
     "title": "Plant Performance & Asset Optimization",
     "subtitle": "Predictive maintenance and OEE intelligence keeping every "
                 "asset productive and efficient."},
    {"id": "supply", "label": "Supply Chain", "short": "Module 4",
     "title": "Autonomous Supply Chain & Execution",
     "subtitle": "From inventory signals to fleet optimization - orchestrating "
                 "supply at machine speed."},
    {"id": "quality", "label": "Quality Leadership", "short": "Module 5",
     "title": "Quality Leadership & Command",
     "subtitle": "Vision inspection, predictive quality and digital twins "
                 "driving lower scrap and safer plants."},
    {"id": "productivity", "label": "Speed, Productivity & AI Copilots",
     "short": "Module 6", "title": "Speed, Productivity & AI Copilots",
     "subtitle": "Production scheduling, knowledge retrieval, and operator "
                 "copilots accelerating every workflow."},
    {"id": "overview", "label": "AI Portfolio Overview", "short": "Overview",
     "title": "AI Portfolio Overview",
     "subtitle": "A composable AI portfolio spanning six modules that work "
                 "standalone or as a unified operating system."},
]


# ---------------------------------------------------------------------------
# Small numeric helpers
# ---------------------------------------------------------------------------
def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def percentile(values, p):
    if not values:
        return 0.0
    s = sorted(values)
    k = (len(s) - 1) * p
    f = math.floor(k)
    c = min(f + 1, len(s) - 1)
    return s[f] + (s[c] - s[f]) * (k - f)


def histogram(values, bins=60, lo=0, hi=59):
    """Count values into `bins` buckets across [lo, hi]."""
    out = [0] * bins
    span = (hi - lo) or 1
    for v in values:
        idx = int((clamp(v, lo, hi) - lo) / span * (bins - 1) + 0.5)
        out[clamp(idx, 0, bins - 1)] += 1
    return out


def smooth(arr, passes=2):
    a = list(arr)
    for _ in range(passes):
        a = [(a[max(0, i - 1)] + a[i] + a[min(len(a) - 1, i + 1)]) / 3.0
             for i in range(len(a))]
    return a


def scale_to(arr, top=100.0):
    m = max(arr) if arr else 0
    if m <= 0:
        return [0 for _ in arr]
    return [round(v / m * top, 2) for v in arr]


def db():
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    return con


# ---------------------------------------------------------------------------
# Per-module aggregation queries
# ---------------------------------------------------------------------------
def q_revenue(con):
    # Funnel from lead journeys
    rows = {r["stage_reached"]: r["n"] for r in con.execute(
        "SELECT stage_reached, COUNT(*) n FROM leads GROUP BY stage_reached")}
    stages = ["Awareness", "Interest", "Consideration", "Loyalty"]
    # count at stage = leads that reached AT LEAST that stage
    totals = [sum(rows.get(s, 0) for s in range(k, 5)) for k in range(1, 5)]
    base = totals[0] or 1
    funnel = [{"stage": stages[i], "count": totals[i],
               "pct": round(totals[i] / base * 100),
               # conversion from the previous stage (100% for the first)
               "conv": 100 if i == 0 else round(totals[i] / (totals[i - 1] or 1) * 100)}
              for i in range(4)]

    # Margin scatter from quotes (AI-priced vs not)
    low = [{"x": r["win_rate"], "y": r["margin"]} for r in con.execute(
        "SELECT win_rate, margin FROM quotes WHERE ai_priced=0")]
    optimal = [{"x": r["win_rate"], "y": r["margin"]} for r in con.execute(
        "SELECT win_rate, margin FROM quotes WHERE ai_priced=1")]
    opt_m = [p["y"] for p in optimal]
    band = {"top": round(percentile(opt_m, 0.75)), "bottom": round(percentile(opt_m, 0.25))}

    # Demand: quarterly order volume vs an 80%-utilization target line
    qrow = {r["q"]: r["u"] for r in con.execute(
        """SELECT CASE WHEN day<91 THEN 0 WHEN day<182 THEN 1
                       WHEN day<273 THEN 2 ELSE 3 END q, SUM(qty) u
           FROM orders GROUP BY q""")}
    units = [qrow.get(i, 0) for i in range(4)]
    mu = max(units) or 1
    forecast = [round(u / mu * 95) for u in units]

    # Monetization: ARR split remote-service vs traditional
    rs = con.execute("SELECT remote_service, SUM(arr) s FROM customers GROUP BY remote_service")
    split = {r["remote_service"]: r["s"] for r in rs}
    rtot = split.get(1, 0) + split.get(0, 0)
    remote = round(split.get(1, 0) / (rtot or 1) * 100)

    # Segmentation radar: average attributes across the customer base
    seg = con.execute("""SELECT AVG(price_sensitivity) a, AVG(service_needs) b,
                         AVG(tech_adoption) c, AVG(growth_potential) d,
                         AVG(risk_profile) e FROM customers""").fetchone()
    return {
        "funnel": funnel,
        "margin": {"low": low, "optimal": optimal, "band": band},
        "demand": {"labels": ["Q1", "Q2", "Q3", "Q4"],
                   "capacity": [80, 80, 80, 80], "forecast": forecast},
        "monetization": {"remoteService": remote, "traditionalSales": 100 - remote},
        "segmentation": {
            "labels": ["Price Sensitivity", "Service Needs", "Tech Adoption",
                       "Growth Potential", "Risk Profile"],
            "values": [round(seg["a"]), round(seg["b"]), round(seg["c"]),
                       round(seg["d"]), round(seg["e"])],
        },
    }


# Support-copilot conversation scripts, keyed by the real ticket issue type.
# {client} is replaced with the actual account name from the ticket queue.
COPILOT_SCRIPTS = {
    "Critical Outage": [
        ("user", "{client}: System A is down — error code 503. What's the fix?"),
        ("ai", "Error 503 is a gateway timeout. I've traced it to the primary gateway router and can restart it remotely. Starting the restart sequence now…"),
        ("user", "We need this resolved ASAP — it's affecting production."),
        ("ai", "Restart complete ✓ System A is back online; service restored in 45s. I've opened an incident and scheduled a root-cause review for the on-call team."),
    ],
    "Performance Degradation": [
        ("user", "{client}: The dashboard has been really slow since this morning."),
        ("ai", "I'm seeing elevated database query latency on your tenant. Pinpointing the slow queries now…"),
        ("ai", "Found it — an unindexed report query. I've applied the cached plan and latency dropped from 4.2s to 380ms. Monitoring for the next hour."),
    ],
    "Data Sync Error": [
        ("user", "{client}: Our inventory data isn't syncing to the ERP."),
        ("ai", "Checking the sync pipeline… the connector hit an auth-token expiry at 02:14."),
        ("ai", "I've refreshed the token and replayed the 1,284 queued records. Sync is green and fully back-filled. Want me to add an auto-renew alert?"),
        ("user", "Yes please."),
        ("ai", "Done — you'll now get a 7-day heads-up before any token expires."),
    ],
    "Integration Help": [
        ("user", "{client}: How do I connect our MES to your API?"),
        ("ai", "Happy to help. For an MES integration you'll use the /v2/events webhook with an HMAC key. I've generated a sandbox key and a sample payload."),
        ("ai", "I've also linked the MES quick-start guide and a Postman collection — most teams are live in under a day."),
    ],
    "Billing Inquiry": [
        ("user", "{client}: Why did this month's invoice go up?"),
        ("ai", "Reviewing your account… the increase is from 3 seats added on the 12th plus metered API usage above your tier."),
        ("ai", "I've itemised both on a revised statement. You'd save ~14% on the next tier up — want a comparison?"),
    ],
    "Feature Request": [
        ("user", "{client}: Can we get CSV export on the analytics view?"),
        ("ai", "Great suggestion — CSV export is on the roadmap for next quarter. I've attached your request to the tracking item and tagged your account."),
        ("ai", "In the meantime the /reports API returns the same data as CSV — I've shared a one-line script you can use today."),
    ],
    "Security Alert": [
        ("user", "{client}: We got an alert about unusual logins on our account."),
        ("ai", "I can see 4 sign-in attempts from a new region in the last hour. As a precaution I've revoked those sessions and required re-authentication."),
        ("ai", "No data was accessed. I recommend enabling enforced SSO + MFA — I've prepared the config and can apply it now with your approval."),
        ("user", "Please enable it."),
        ("ai", "Enforced SSO + MFA is live across your workspace ✓ I've emailed the audit log to your security contact."),
    ],
    "Onboarding Request": [
        ("user", "{client}: We just signed up — how do we get our team started?"),
        ("ai", "Welcome aboard! I've provisioned your workspace and created admin invites for your 3 listed owners."),
        ("ai", "I've queued a guided setup: data connectors, role mapping, and a sample dashboard. Want me to book a 30-min onboarding call with a specialist?"),
        ("user", "Yes, next week works."),
        ("ai", "Booked for Tuesday 10:00 ✓ Calendar invites sent. You're all set to start exploring today."),
    ],
}
DEFAULT_SCRIPT = [
    ("user", "{client}: I need help with an issue on our account."),
    ("ai", "I'm on it — pulling up your account context and recent activity now…"),
    ("ai", "I've identified the most likely cause and prepared a fix. Applying it and confirming the result for you."),
]

# Contract clauses an LLM extractor would flag, worst first.
CLAUSE_CATALOG = [
    ("Uncapped liability for downtime", "high",
     "…supplier liability for downtime exceeding 2 hours shall not be capped…"),
    ("Unilateral price escalation", "high",
     "…supplier may increase pricing by up to 12% annually at its sole discretion…"),
    ("Auto-renewal without notice window", "medium",
     "…this agreement renews automatically unless terminated 90 days in advance…"),
    ("Late-delivery penalties waived", "medium",
     "…penalties for late delivery are waived under broadly-defined force majeure…"),
    ("Weak IP indemnification", "low",
     "…IP-claim indemnification is limited to fees paid in the prior 3 months…"),
]
SLA_HOURS = {"high": 4, "medium": 24, "low": 72}


def q_commercial(con):
    # --- High-value prioritization (real open tickets + value at risk) -----
    open_total = con.execute("SELECT COUNT(*) n FROM tickets WHERE status='open'").fetchone()["n"]
    pri = []
    for r in con.execute("""SELECT t.issue, t.severity, t.risk_score, t.value_at_risk,
                            c.name FROM tickets t JOIN customers c ON c.id=t.customer_id
                            WHERE t.status='open' ORDER BY t.risk_score DESC LIMIT 4"""):
        label = {"high": "High", "medium": "Medium", "low": "Low"}[r["severity"]]
        pri.append({"client": r["name"], "issue": r["issue"],
                    "riskScore": round(r["risk_score"]), "priority": r["severity"],
                    "label": label, "valueAtRisk": round(r["value_at_risk"]),
                    "sla": SLA_HOURS[r["severity"]]})

    # --- Support-copilot scenarios across ALL distinct issue types ---------
    # (one representative real account per issue, highest-value first)
    scenarios, seen = [], set()
    for r in con.execute("""SELECT t.issue, c.name, c.contact, t.value_at_risk FROM tickets t
                            JOIN customers c ON c.id=t.customer_id
                            ORDER BY t.value_at_risk DESC"""):
        if r["issue"] in seen:
            continue
        seen.add(r["issue"])
        script = COPILOT_SCRIPTS.get(r["issue"], DEFAULT_SCRIPT)
        scenarios.append({"title": r["issue"], "client": r["name"], "contact": r["contact"],
                          "messages": [{"role": role, "text": txt.replace("{client}", r["contact"])}
                                       for role, txt in script]})

    # --- Supplier risk: markers + ranked list, elevated by LIVE quakes -----
    quakes = live.get_quakes() or []
    elevated = 0
    markers, ranked = [], []
    for r in con.execute("""SELECT name, country, map_x, map_y, on_time_rate, risk_score
                            FROM suppliers"""):
        lat, lon = pixel_to_latlon(r["map_x"], r["map_y"])
        boost, near = 0.0, None
        for qk in quakes:
            dist = live.haversine_km(lat, lon, qk["lat"], qk["lon"])
            if dist < 2000 and qk["mag"]:
                b = qk["mag"] * 6 * (1 - dist / 2000)
                if b > boost:
                    boost, near = b, qk
        risk = clamp(r["risk_score"] + boost, 0, 100)
        if boost > 5:
            elevated += 1
        color = "#d8581f" if risk >= 60 else "#e7a93a" if risk >= 30 else "#5e9f55"
        band = "high" if risk >= 60 else "medium" if risk >= 30 else "low"
        reason = ("M%.1f quake nearby (live)" % near["mag"]) if (near and boost > 5) \
            else "%d%% on-time delivery" % round(r["on_time_rate"] * 100)
        markers.append({"x": r["map_x"], "y": r["map_y"], "color": color,
                        "name": r["name"], "country": r["country"],
                        "risk": round(risk), "band": band, "reason": reason})
        ranked.append({"name": r["name"], "country": r["country"], "risk": round(risk),
                       "band": band, "reason": reason})
    ranked.sort(key=lambda x: x["risk"], reverse=True)

    # --- Contract intelligence: flagged clauses (linked to supplier risk) --
    flags = []
    for i, s in enumerate(ranked):
        if s["risk"] >= 30:
            clause, lvl, excerpt = CLAUSE_CATALOG[i % len(CLAUSE_CATALOG)]
            flags.append({"supplier": s["name"], "clause": clause, "level": lvl,
                          "excerpt": excerpt})
    contracts = {"analyzed": len(ranked), "flagged": len(flags), "topFlags": flags[:4]}

    # --- Next-best-action: the highest-upside account ----------------------
    top = con.execute("""SELECT name, segment, arr, upsell_score
                         FROM customers ORDER BY upsell_score DESC LIMIT 1""").fetchone()
    uplift = clamp(round(top["upsell_score"] * 0.35), 5, 40)
    conf = clamp(round(60 + top["upsell_score"] * 0.35), 80, 99)
    days = clamp(round(2 + (100 - top["upsell_score"]) / 22), 2, 7)
    action = ("Propose premium service tier to %s (%s) based on usage and growth signals."
              % (top["name"], top["segment"]))
    return {
        "prioritization": {"cases": pri, "openTotal": open_total},
        "copilot": {"scenarios": scenarios},
        "supplierMarkers": markers,
        "supplierTop": ranked[:5],
        "supplierLive": {"quakes": len(quakes), "elevated": elevated, "live": bool(quakes)},
        "contracts": contracts,
        "insight": {"action": action, "arrUplift": "+%d%%" % uplift,
                    "confidence": "%d%%" % conf, "toClose": "%dd" % days},
    }


def q_plant(con):
    # Per-line availability from raw OEE shifts (drives per-asset utilization)
    line_avail = {}
    for r in con.execute("""SELECT line_id, (SUM(planned_min)-SUM(downtime_min))
                            *1.0/SUM(planned_min) a FROM oee_shifts GROUP BY line_id"""):
        line_avail[r["line_id"]] = r["a"]
    line_names = {r["id"]: r["name"] for r in con.execute("SELECT id, name FROM lines")}

    # All assets: reliability risk + utilization + status + detail (emergent)
    assets, worst = [], None
    for a in con.execute("""SELECT id, name, kind, line_id, age_hours,
                            weibull_shape, weibull_scale FROM assets"""):
        risk = 1.0 - math.exp(-((a["age_hours"] / a["weibull_scale"]) ** a["weibull_shape"]))
        if worst is None or risk > worst[0]:
            worst = (risk, a)
        # utilization = line availability, derated by this machine's wear
        util = clamp(round((line_avail.get(a["line_id"], 0.85)) * 100 * (1 - 0.45 * risk)), 8, 99)
        if risk >= 0.65:
            status, label, color = "maintenance", "Maintenance due", "#d8581f"
        elif util < 66:
            status, label, color = "idle", "Underutilized", "#e7a93a"
        else:
            status, label, color = "running", "Running", "#5e9f55"
        # per-asset remaining useful life (mean residual life)
        mlife = a["weibull_scale"] * math.gamma(1 + 1 / a["weibull_shape"])
        rul = int(clamp(round(mlife - a["age_hours"]), 0, 9999))
        rec = ("Schedule maintenance now — failure risk is high." if status == "maintenance"
               else "Rebalance load — this asset is underutilized." if status == "idle"
               else "Operating normally — no action needed.")
        assets.append({"name": a["name"], "kind": a["kind"], "utilization": util,
                       "status": status, "statusLabel": label, "color": color,
                       "line": line_names.get(a["line_id"], "—"),
                       "risk": round(risk * 100), "rul": rul,
                       "agePct": round(a["age_hours"] / a["weibull_scale"] * 100),
                       "recommendation": rec})
    assets.sort(key=lambda x: x["utilization"], reverse=True)
    overall_util = round(sum(x["utilization"] for x in assets) / (len(assets) or 1))
    counts = {"running": 0, "idle": 0, "maintenance": 0}
    for x in assets:
        counts[x["status"]] += 1

    # Predictive maintenance: the highest-risk asset
    risk, a = worst
    # Mean residual life: Weibull mean (scale * Gamma(1+1/shape)) minus current age.
    # Aged/over-life assets yield a small RUL => genuine maintenance urgency.
    mean_life = a["weibull_scale"] * math.gamma(1 + 1 / a["weibull_shape"])
    hours = int(clamp(round(mean_life - a["age_hours"]), 4, 720))

    # OEE from raw shift records: Availability x Performance x Quality
    o = con.execute("""SELECT SUM(planned_min) p, SUM(downtime_min) d,
                        SUM((planned_min-downtime_min)*ideal_rate) ideal,
                        SUM(good_units) g, SUM(scrap_units) s FROM oee_shifts""").fetchone()
    A = (o["p"] - o["d"]) / o["p"]
    produced = o["g"] + o["s"]
    P = clamp(produced / (o["ideal"] or 1), 0, 1)
    Q = o["g"] / (produced or 1)
    avail_loss = round((1 - A) * 100, 1)
    perf_loss = round(A * (1 - P) * 100, 1)
    qual_loss = round(A * P * (1 - Q) * 100, 2)
    actual = round(A * P * Q * 100, 1)

    # Energy: quarterly production volume vs unit utility cost (learning curve)
    eq = con.execute("SELECT quarter, units, cost_per_unit FROM energy_quarter ORDER BY quarter").fetchall()
    units = [r["units"] for r in eq]
    cpu = [r["cost_per_unit"] for r in eq]
    facility = [{"label": r["name"], "value": r["value"], "color": r["color"],
                 "icon": r["icon"]} for r in con.execute(
        "SELECT name, value, color, icon FROM facility_metrics ORDER BY sort")]
    # --- Overlay LIVE signals onto the facility gauges ---------------------
    carbon = live.get_carbon()
    if carbon and carbon.get("gco2") is not None:
        cidx = (carbon.get("index") or "").lower()
        ccolor = ("#5e9f55" if cidx in ("very low", "low") else
                  "#e7a93a" if cidx == "moderate" else "#d8581f")
        facility[1] = {"label": "Grid Carbon (live)", "value": str(carbon["gco2"]),
                       "color": ccolor, "icon": "\U0001F30D"}
    wx = live.get_weather()
    if wx and wx.get("temp_c") is not None:
        # HVAC load rises as ambient temp departs from a 21C setpoint
        load = clamp(40 + abs(wx["temp_c"] - 21) * 2.2, 30, 95)
        facility[0] = {"label": "HVAC Load (live %.0f°C)" % wx["temp_c"],
                       "value": "%.1f" % load, "color": "#1f4e9b", "icon": "\U0001F321"}
    return {
        "maintenance": {"hoursToFailure": hours, "risk": round(risk, 2),
                        "asset": a["name"], "kind": a["kind"]},
        "assetUtil": {"assets": assets, "overall": overall_util, "counts": counts},
        "oee": {"availabilityLoss": avail_loss, "performanceLoss": perf_loss,
                "qualityLoss": qual_loss, "actualOEE": actual},
        "energy": {"labels": ["Q1", "Q2", "Q3", "Q4"],
                   "production": [round(v) for v in scale_to(units, 85)],
                   "costPerUnit": [round(v) for v in scale_to(cpu, 85)]},
        "facility": facility,
    }


def q_supply(con):
    # Inventory: per-SKU days-of-cover -> two populations (stock-out vs excess)
    fast, slow = [], []
    for r in con.execute("SELECT on_hand, daily_demand, mover FROM skus"):
        cover = r["on_hand"] / (r["daily_demand"] or 1)
        (fast if r["mover"] == "fast" else slow).append(cover)
    stockout = scale_to(smooth(histogram(fast, 60, 0, 59)), 100)
    excess = scale_to(smooth(histogram(slow, 60, 0, 59)), 100)

    vendors = [{"name": r["name"], "trustScore": round(r["trust_score"]),
                "onTime": round(r["on_time_rate"] * 100), "quality": round(r["quality_rate"] * 100)}
               for r in con.execute("""SELECT name, trust_score, on_time_rate, quality_rate
                                       FROM vendors ORDER BY trust_score DESC""")]

    # Fleet: live vehicle/route status (delayed first)
    fleet = [{"vehicle": r["vehicle"], "route": r["route"], "status": r["status"],
              "eta": r["eta_hours"], "load": r["load_pct"], "reason": r["delay_reason"]}
             for r in con.execute("""SELECT vehicle, route, status, eta_hours, load_pct,
                                     delay_reason FROM shipments
                                     ORDER BY status='delayed' DESC, eta_hours DESC""")]
    on_time = sum(1 for f in fleet if f["status"] == "on-time")

    # Warehouse slotting zones (ABC) + derived KPIs
    zones = [{"zone": z["zone"], "klass": z["klass"], "utilization": z["utilization"],
              "picks": z["picks_per_hr"], "travel": z["travel_m"], "reslot": bool(z["reslot"])}
             for z in con.execute("""SELECT zone, klass, utilization, picks_per_hr,
                                     travel_m, reslot FROM wh_zones ORDER BY id""")]
    tot_picks = sum(z["picks"] for z in zones) or 1
    # pick efficiency: share of picks coming from low-travel (fast) zones
    fast_picks = sum(z["picks"] for z in zones if z["klass"] == "Fast")
    avg_travel = round(sum(z["travel"] * z["picks"] for z in zones) / tot_picks, 1)
    warehouse = {"zones": zones, "pickEfficiency": round(fast_picks / tot_picks * 100),
                 "avgTravel": avg_travel, "reslotSuggestions": sum(1 for z in zones if z["reslot"])}

    # Back-office automation: orders -> invoices. "Standard" orders (margin in the
    # normal band) auto-process straight-through; outliers need manual review.
    bo = con.execute("""SELECT COUNT(*) total,
                        SUM(CASE WHEN margin BETWEEN 28 AND 48 THEN 1 ELSE 0 END) auto
                        FROM orders""").fetchone()
    total_docs, auto_docs = bo["total"], (bo["auto"] or 0)
    auto_rate = round(auto_docs / (total_docs or 1) * 100)
    backoffice = {"documents": total_docs, "autoRate": auto_rate,
                  "manual": total_docs - auto_docs,
                  "hoursSaved": round(auto_docs * 4 / 60),   # ~4 min saved/doc
                  "steps": ["Data Entry", "Validation", "Document Generation"]}
    return {
        "inventory": {"labels": list(range(60)),
                      "stockoutRisk": stockout, "excessStock": excess},
        "vendors": vendors,
        "fleet": {"vehicles": fleet, "onTime": on_time, "delayed": len(fleet) - on_time,
                  "total": len(fleet)},
        "warehouse": warehouse,
        "backoffice": backoffice,
    }


def q_quality(con):
    # Quality distribution: deviation -> quality score histogram, rework cutoff
    scores = []
    for r in con.execute("SELECT deviation FROM inspections"):
        scores.append(clamp(round(60 - 2 * r["deviation"]), 0, 59))
    dist = scale_to(smooth(histogram(scores, 60, 0, 59), 2), 100)
    threshold = clamp(round(60 - 2 * 14), 0, 59)  # dev=14 => p(rework)=0.5

    # Defects: the most recent inspection that actually has bounding boxes
    insp = con.execute("SELECT MAX(inspection_id) id FROM defects").fetchone()
    boxes = []
    if insp and insp["id"] is not None:
        boxes = [{"x": r["x"], "y": r["y"], "w": r["w"], "h": r["h"], "kind": r["kind"]}
                 for r in con.execute(
                     "SELECT x,y,w,h,kind FROM defects WHERE inspection_id=?", (insp["id"],))]
    # overall scrap rate (share of inspections that needed rework) -> pass rate
    rw = con.execute("SELECT AVG(rework) r FROM inspections").fetchone()["r"] or 0
    pass_rate = round((1 - rw) * 100, 1)

    # Digital twin: latest sensor reading per metric
    twin = con.execute("SELECT id FROM assets WHERE is_twin=1 LIMIT 1").fetchone()["id"]
    dt = []
    fmt = {"Pressure": ("%d%%", 100.0), "Temperature": ("%d°C", 80.0),
           "Speed": ("%d RPM", 3500.0)}
    for metric in ("Pressure", "Temperature", "Speed"):
        v = con.execute("""SELECT value FROM sensor_readings WHERE asset_id=? AND metric=?
                           ORDER BY ts DESC LIMIT 1""", (twin, metric)).fetchone()["value"]
        f, vmax = fmt[metric]
        dt.append({"label": metric, "value": f % round(v),
                   "pct": clamp(round(v / vmax * 100), 5, 99)})

    safety = con.execute("SELECT incidents FROM safety_quarter ORDER BY quarter").fetchall()

    # Root cause: aggregate every defect by its 6M category (Method/Machine/Material)
    cause_map = {"scratch": "Material", "porosity": "Material", "dent": "Machine",
                 "crack": "Machine", "misalignment": "Method"}
    tally = {"Method": 0, "Machine": 0, "Material": 0}
    for r in con.execute("SELECT kind, COUNT(*) n FROM defects GROUP BY kind"):
        tally[cause_map.get(r["kind"], "Method")] += r["n"]
    tot = sum(tally.values()) or 1
    drivers = sorted(({"name": k, "pct": round(v / tot * 100)} for k, v in tally.items()),
                     key=lambda d: d["pct"], reverse=True)
    return {
        "qualityDist": {"labels": list(range(60)), "values": dist,
                        "reworkThreshold": threshold},
        "defects": {"boxes": boxes, "count": len(boxes),
                    "verdict": "FAIL" if boxes else "PASS", "passRate": pass_rate},
        "rootCause": {"drivers": drivers, "top": drivers[0]["name"], "total": tot},
        "digitalTwin": dt,
        "safety": {"labels": ["Q1", "Q2", "Q3", "Q4"],
                   "incidents": [r["incidents"] for r in safety]},
    }


# Operator-copilot troubleshooting steps + symptom, keyed by machine kind.
OPERATOR_STEPS = {
    "CNC Mill": ("spindle overheat warning",
                 [("Check spindle load & temp", "⚙"), ("Inspect tooling for wear", "🔍"),
                  ("Recalibrate X/Y axis", "⟳"), ("Run a test cut & verify", "✓"),
                  ("Log the report", "📄")]),
    "Press": ("tonnage deviation alert",
              [("Check hydraulic pressure", "⚙"), ("Inspect die alignment", "🔍"),
               ("Reset the PLC controller", "⟳"), ("Cycle & confirm tonnage", "✓"),
               ("Log the report", "📄")]),
    "Turbine": ("vibration threshold exceeded",
                [("Read the vibration sensor", "⚙"), ("Inspect blade surfaces", "🔍"),
                 ("Balance the rotor assembly", "⟳"), ("Monitor a 10-min run", "✓"),
                 ("Log the report", "📄")]),
    "Conveyor": ("belt-slip fault",
                 [("Check belt tension", "⚙"), ("Inspect drive rollers", "🔍"),
                  ("Clear any obstruction", "⟳"), ("Restart & verify speed", "✓"),
                  ("Log the report", "📄")]),
    "Robot Arm": ("axis-drift error E-404",
                  [("Check joint encoders", "⚙"), ("Inspect gripper seals", "🔍"),
                   ("Re-home all axes", "⟳"), ("Run a test cycle", "✓"),
                   ("Log the report", "📄")]),
}
DEFAULT_OP = ("fault detected", [("Run diagnostics", "⚙"), ("Inspect the unit", "🔍"),
                                 ("Apply the fix", "⟳"), ("Verify operation", "✓"),
                                 ("Log the report", "📄")])

# Engineering-KB search scenarios: a query + the keywords used to rank documents.
KB_QUERIES = [
    ("How do I service the hydraulic pump?", ["pump", "hydraulic", "maintenance"]),
    ("Sensor calibration steps", ["sensor", "calibration"]),
    ("Lockout / tagout safety procedure", ["safety", "lockout", "compliance"]),
    ("Gearbox alignment spec", ["gearbox", "alignment"]),
    ("Troubleshooting model X-100", ["troubleshooting", "x-100", "model"]),
]


def q_productivity(con):
    run_c, change_c = "#16345f", "#e7a93a"
    schedule, order = {}, {}
    runmonths = {}
    for r in con.execute("""SELECT line_id, name, start_month, end_month, kind
                            FROM schedule_runs ORDER BY line_id, start_month"""):
        if r["name"] not in schedule:
            schedule[r["name"]] = []
            order[r["name"]] = r["line_id"]
            runmonths[r["name"]] = 0
        schedule[r["name"]].append({"s": r["start_month"], "e": r["end_month"],
                                    "kind": r["kind"],
                                    "c": run_c if r["kind"] == "run" else change_c})
        if r["kind"] == "run":
            runmonths[r["name"]] += r["end_month"] - r["start_month"]
    sched = [{"name": n, "segs": schedule[n], "runPct": round(runmonths[n] / 12 * 100)}
             for n in sorted(schedule, key=lambda x: order[x])]

    # Operator copilot scenarios from real machines (distinct kinds)
    ops, kinds_seen = [], set()
    for a in con.execute("SELECT name, kind FROM assets ORDER BY age_hours DESC"):
        if a["kind"] in kinds_seen:
            continue
        kinds_seen.add(a["kind"])
        symptom, steps = OPERATOR_STEPS.get(a["kind"], DEFAULT_OP)
        ops.append({"asset": a["name"], "kind": a["kind"],
                    "query": "Troubleshoot %s — %s" % (a["name"], symptom),
                    "steps": [{"n": i + 1, "text": t, "icon": ic}
                              for i, (t, ic) in enumerate(steps)]})
        if len(ops) >= 4:
            break

    # Engineering KB: rank documents per query by keyword + base relevance
    docs = [{"title": r["title"], "icon": r["icon"], "type": r["doc_type"],
             "rel": r["relevance"], "low": r["title"].lower()}
            for r in con.execute("SELECT title, icon, doc_type, relevance FROM kb_documents")]
    kb_queries = []
    for q, keys in KB_QUERIES:
        scored = []
        for d in docs:
            overlap = sum(1 for k in keys if k in d["low"])
            score = 0.45 * d["rel"] + 0.55 * (overlap / len(keys))
            scored.append((score, d))
        scored.sort(key=lambda s: s[0], reverse=True)
        results = [{"title": d["title"], "icon": d["icon"], "type": d["type"],
                    "match": int(clamp(round(sc * 100), 40, 99))}
                   for sc, d in scored[:3]]
        kb_queries.append({"q": q, "results": results})

    # AI service desk: real triage funnel from ticket statuses
    sd = {r["status"]: r["n"] for r in con.execute(
        "SELECT status, COUNT(*) n FROM tickets GROUP BY status")}
    incoming = sum(sd.values()) or 1
    resolved = sd.get("resolved", 0)
    serviceDesk = {"incoming": incoming, "triaged": sd.get("triaged", 0),
                   "resolved": resolved, "open": sd.get("open", 0),
                   "autoResolvePct": round(resolved / incoming * 100)}

    # Alert prioritization: a real cross-signal feed (assets, supply, inventory, live)
    alerts = []
    for r in con.execute("""SELECT name, kind, age_hours, weibull_shape, weibull_scale
                            FROM assets"""):
        risk = 1.0 - math.exp(-((r["age_hours"] / r["weibull_scale"]) ** r["weibull_shape"]))
        if risk >= 0.6:
            alerts.append({"level": "high" if risk >= 0.8 else "medium",
                           "title": "%s — failure risk %d%%" % (r["name"], round(risk * 100)),
                           "source": "Predictive Maintenance", "score": risk})
    low_cov = con.execute("""SELECT COUNT(*) n FROM skus
                             WHERE on_hand*1.0/daily_demand < lead_time_days""").fetchone()["n"]
    if low_cov:
        alerts.append({"level": "high" if low_cov > 8 else "medium",
                       "title": "%d SKUs below lead-time cover (stock-out risk)" % low_cov,
                       "source": "Inventory", "score": 0.7 + low_cov / 100})
    quakes = live.get_quakes() or []
    big = [q for q in quakes if (q.get("mag") or 0) >= 5.5]
    if big:
        alerts.append({"level": "high", "title": "M%.1f quake near supply region — %s"
                       % (big[0]["mag"], (big[0]["place"] or "")[:42]),
                       "source": "Supplier Risk (live)", "score": 0.9})
    hot = con.execute("SELECT COUNT(*) n FROM tickets WHERE severity='high' AND status='open'").fetchone()["n"]
    if hot:
        alerts.append({"level": "medium", "title": "%d high-risk support cases open" % hot,
                       "source": "Service Desk", "score": 0.65})
    alerts.sort(key=lambda x: x["score"], reverse=True)
    for x in alerts:
        x.pop("score", None)
    return {"schedule": sched, "operators": ops, "knowledgeBase": kb_queries,
            "serviceDesk": serviceDesk, "alerts": alerts[:6]}


def q_overview(con):
    o = con.execute("""SELECT SUM(planned_min) p, SUM(downtime_min) d,
                       SUM((planned_min-downtime_min)*ideal_rate) ideal,
                       SUM(good_units) g, SUM(scrap_units) s FROM oee_shifts""").fetchone()
    A = (o["p"] - o["d"]) / o["p"]
    produced = o["g"] + o["s"]
    P = clamp(produced / (o["ideal"] or 1), 0, 1)
    Q = o["g"] / (produced or 1)
    oee = round(A * P * Q * 100)

    # forecast accuracy proxy: how often the quote win_rate predicted the outcome
    qr = con.execute("""SELECT AVG(CASE WHEN (win_rate>=50)=(won=1) THEN 1.0 ELSE 0 END) acc
                        FROM quotes""").fetchone()["acc"]
    accuracy = round((qr or 0) * 100)

    uplift = con.execute("SELECT SUM(arr*upsell_score/100.0) u FROM customers").fetchone()["u"]

    # --- LIVE KPIs from public APIs ---------------------------------------
    carbon = live.get_carbon()
    fx = live.get_fx()
    quakes = live.get_quakes() or []
    disruptions = sum(1 for q in quakes if (q.get("mag") or 0) >= 5.0)
    eur = (fx or {}).get("rates", {}).get("EUR")

    kpis = [{"label": "Avg OEE", "value": "%d%%" % oee, "delta": "internal"}]
    if carbon and carbon.get("gco2") is not None:
        kpis.append({"label": "Grid Carbon", "value": "%s g" % carbon["gco2"],
                     "delta": "LIVE · %s" % carbon.get("index", "")})
    else:
        kpis.append({"label": "Forecast Accuracy", "value": "%d%%" % accuracy, "delta": "model"})
    if eur:
        kpis.append({"label": "USD / EUR", "value": "%.3f" % eur, "delta": "LIVE · ECB"})
    else:
        kpis.append({"label": "ARR Uplift", "value": "$%.1fM" % (uplift / 1000.0), "delta": "pipeline"})
    kpis.append({"label": "Active Disruptions", "value": str(disruptions),
                 "delta": "LIVE · M5+ /24h" if quakes else "offline"})
    return {"kpis": kpis}


QUERIES = {
    "revenue": q_revenue, "commercial": q_commercial, "plant": q_plant,
    "supply": q_supply, "quality": q_quality, "productivity": q_productivity,
    "overview": q_overview,
}


def module_data(mid):
    con = db()
    try:
        return QUERIES[mid](con)
    finally:
        con.close()


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------
class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def log_message(self, fmt, *args):
        print("  %s - %s" % (self.address_string(), fmt % args), flush=True)

    def _send_json(self, payload, status=200):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = self.path.split("?", 1)[0].rstrip("/")

        if path == "/api/health":
            return self._send_json({"status": "ok", "time": time.time(),
                                    "live": live.status(), "anyLive": live.any_live()})

        if path == "/api/live":
            return self._send_json({
                "status": live.status(), "anyLive": live.any_live(),
                "quakes": (live.get_quakes() or [])[:8],
                "carbon": live.get_carbon(), "fx": live.get_fx(),
                "weather": live.get_weather(), "macro": live.get_macro(),
                "plant": live.PLANT,
            })

        if path == "/api/modules":
            return self._send_json({"modules": MODULES})

        if path == "/api/reseed":
            seed.main()
            return self._send_json({"status": "reseeded"})

        if path.startswith("/api/module/"):
            mid = path[len("/api/module/"):]
            if mid not in QUERIES:
                return self._send_json({"error": "unknown module '%s'" % mid}, 404)
            try:
                return self._send_json({"id": mid, "data": module_data(mid)})
            except Exception as e:  # surface query errors as JSON, don't 500 silently
                return self._send_json({"error": "%s: %s" % (type(e).__name__, e)}, 500)

        if path.startswith("/api/"):
            return self._send_json({"error": "not found"}, 404)

        if self.path in ("/", ""):
            self.path = "/index.html"
        return super().do_GET()


def main():
    if not DB_PATH.exists():
        print("dashboard.db not found - seeding...", flush=True)
        seed.main()
    print("Warming live data sources (USGS, Open-Meteo, ECB, Carbon, World Bank)...",
          flush=True)
    live.start_refresher(interval=120)  # keep live cache fresh in the background
    # Port: CLI arg, else $PORT, else 8000. Host: $HOST (0.0.0.0 in containers/HF), else localhost.
    port = int(sys.argv[1]) if len(sys.argv) > 1 else int(os.environ.get("PORT", "8000"))
    host = os.environ.get("HOST", "127.0.0.1")
    httpd = ThreadingHTTPServer((host, port), Handler)
    shown = "127.0.0.1" if host in ("127.0.0.1", "0.0.0.0") else host
    print("AI Portfolio Dashboard running on %s:%d" % (host, port))
    print("   Frontend : http://%s:%d/" % (shown, port))
    print("   API      : http://%s:%d/api/module/revenue" % (shown, port))
    print("   Live     : http://%s:%d/api/live" % (shown, port))
    print("Press Ctrl+C to stop.", flush=True)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        httpd.shutdown()


if __name__ == "__main__":
    main()
